### PR TITLE
Update loopback labels

### PR DESCRIPTION
**Pull request by superkhau**
Connect to strongloop-internal/scrum-loopback/issues/627

### CODE REVIEW

**Comment by superkhau** [comment]
@rmg Review please.

**Comment by rmg** [comment]
@superkhau you need to learn the art of `git add -p` :bow: 

Other than that, rubber-stamp LGTM I guess. Not my tool, not my repos, not my scrum board...

**Comment by sam-github** [comment]
@superkhau this doesn't need LGTM if its not a code change, its just the loopback config, change it as you wish

**Comment by superkhau** [comment]
>

@superkhau you need to learn the art of git add -p :bow:

Other than that, rubber-stamp LGTM I guess. Not my tool, not my repos, not my scrum board...

I just mashed it in TBH, but yes `git add -p` next time. :bow:

>@superkhau this doesn't need LGTM if its not a code change, its just the loopback config, change it as you wish

Cool, TY. :racehorse:

**Pull request merged**
