### PR TITLE
Report tool integration

### PR DESCRIPTION
**Pull request by sam-github**
Connect to strongloop-internal/scrum-nodeops#305

### CODE REVIEW

**Comment by chandadharap** [comment]
Am not sure how to run this? bin is missing. so i ran the test in the test folder, but threw an error. tried a few other things. obviously im missing s key instruction :-)

**Comment by sam-github** [comment]
example: `./bin/report.js strongloop-internal/scrum-nodeops 334`

**Comment by sam-github** [comment]
You need to call `npm install`, too, after checking out this branch.

**Comment by chandadharap** [comment]
well.. i did do npm install. problem, is there is no bin folder isn't it? 
Chandas-MacBook-Pro:github-tools chanda$ ls -lt
total 16
drwxr-xr-x  10 chanda  staff   340 Mar 11 22:13 node_modules
drwxr-xr-x   9 chanda  staff   306 Mar 11 22:10 lib
-rw-r--r--   1 chanda  staff   570 Mar 11 22:10 package.json
drwxr-xr-x   5 chanda  staff   170 Mar 11 22:10 projects
drwxr-xr-x   3 chanda  staff   102 Mar 11 22:10 test
-rw-r--r--   1 chanda  staff  1271 Nov 10 22:27 README.md

**Comment by sam-github** [comment]
@chandadharap check it out. In particular, check out the output from nodeops.json, which I just comitted for your perusal: https://github.com/strongloop-internal/github-tools/blob/report/nodeops.txt

Note that it has a table at the end, which is a nice view of the data we have.

Preceeding that table is basically a raw dump, useful for answering the question "what does that number in the table mean".

Headings are hopefully clear, but very short to keep table page-width:
```
sprint │ c  │ PR │ bug │ issue │ inc │ PR │ bug │ issue │ rej │ rej, PR │ rej, issue 
```

sprint, total complete, complete: PR, complete: bug, complete: issue, incomplete, incomplete:PR, etc...

Take a poke, try to find errors, and look at the data, see what better categorization of work might be possible.

**Comment by sam-github** [comment]
Also, note well that I only report on issues that have had a state change since this date: https://github.com/strongloop-internal/github-tools/blob/report/lib/report.js#L84

Feel free to crank that number back 6 months to see more data. There's no reason in principal not to, except for github rate limiting... another story. I'm sure I can fix that.

Also, I added the loopback numbers, here's direct links to the tables:

- loopback: https://github.com/strongloop-internal/github-tools/blob/report/loopback.txt#L646
- nodeops: https://github.com/strongloop-internal/github-tools/blob/report/nodeops.txt#L436

**Comment by sam-github** [comment]
@chandadharap I disabled the 5 second timeout that we'd applied, that seems to be the cause of the gateway errors (which are not actually gateway errors, they are literally a timout in the github client, wherein it aborts if the response isn't fast enough, and lies and says its the gateway). Anyhow, I hit it every time, then never hit it after changing the timeout to 100s of seconds.

Also, I found a caching layer, which should allow the reporter to be run repeatedly with low/no load on the server.

I also added some code to attempt to backoff after hitting the request limit... but I'm hitting it anyhow now, must have been hammering the API too hard. Anyhow, honest-go-goodness github rate limiting has a really obvious error: `Error: {"message":"API rate limit exceeded for sam-github."...`. You'll know if you hit it.

Btw, nodeops.txt is my generation of the report, as of now. loopback.txt is old... I'm rate-limited. :-(

**Comment by sam-github** [comment]
Oh, and I added a dependency, run npm install after updating.

**Comment by rmg** [comment]
5000/hr seems like a generous amount.. until you hit it.

**Pull request closed without merging**
